In [1]:
import numpy as np

### Creating 3*3 array

In [2]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
list_3 = [7,8,9]

In [3]:
np.array([list_1, list_2, list_3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
list_1 = [2,3,4,5]
list_2 = [7,8,9,6]

a = np.array(list_1)
b = np.array(list_2)

list(a*b)

[14, 24, 36, 30]

In [5]:
n = np.array()

TypeError: Required argument 'object' (pos 1) not found

**List is heterogeneous**

In [ ]:
l = [1, 2.5]
l

In [ ]:
type(l)

**Np Array is homogeneous**

In [ ]:
n = np.array(l)
n

**Identity Matrix**

In [ ]:
np.eye(2)

In [ ]:
np.eye(2)

In [ ]:
np.eye(3)

 **Constant value array**

In [ ]:
np.full((2,3),5)

**Repeat Array**

In [ ]:
a = np.array([1,2,3])
b = np.tile(a, 3)
print(b)
b.resize(3,3)
print(b)


**Random Number Array**

In [ ]:
n= np.random.randint(1,10, (5,5)) #(low, hight, size)
n

**Checkboard Matrix**

In [ ]:
np.tile([0,1], 3)

In [ ]:
a = np.zeros((3,3))
a[0::2,1::2] =1
a[1::2,0::2] = 1
#a[0::2,1::2] = 1

#x[1::2, 0::2] = 1
#x[::2, 1::2] = 1
a

In [ ]:
list_1 = [10,11,12,13]
list_2 = [15,12,13,14] 

In [ ]:
arr = np.array([list_1, list_2])

In [ ]:
arr.shape[0]

** Fetch Border element of 2D array **

In [ ]:
arr = np.array([[11,12, 13, 14],
                 [21 ,22, 23, 24],
                 [31 ,32, 33, 34]])

col_first = arr[:,0]
row_first = arr[0,:]
col_last = arr[:,-1]
row_last = arr[-1,:]

print(col_first) 
print(row_first) 
print(col_last) 
print(row_last) 

** HStack & VStack **

In [ ]:
list_1 = [[1, 2], [5, 6]]
list_2 = [[3, 4], [7, 8]]
list_3 = [[9, 10, 11, 12]]

h1 = np.hstack(list_1)
h2 = np.hstack(list_2)
v3 = np.vstack(list_3)

print(h1)
print(h2)
print(v3)


** Vectorize Function ** 

Internally it will create loop and performce function operation on each element of array

In [ ]:
func = np.vectorize(lambda x : x *10)
func(v3)

** Numpy Linear algebra functions **

Find inverse, eigenvalues, eigenvectors, determinants 

In [ ]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
list_3 = [7,8,9]
array_1 = np.array([list_1,list_2,list_3])
eigen = np.linalg.eig(array_1)
#eigenVal = np.linalg.eigvals(array_1)
inv = np.linalg.inv(array_1)
det = np.linalg.det(array_1)
print(eigen)
#print(eigenVal)
print(inv)
print(det)

In [2]:
a = np.array(np.arange(1,133)).reshape(11,12)

In [4]:
a[8,3]

100

In [5]:
a[:,:3]

array([[  1,   2,   3],
       [ 13,  14,  15],
       [ 25,  26,  27],
       [ 37,  38,  39],
       [ 49,  50,  51],
       [ 61,  62,  63],
       [ 73,  74,  75],
       [ 85,  86,  87],
       [ 97,  98,  99],
       [109, 110, 111],
       [121, 122, 123]])

In [15]:
arr = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

In [26]:
arr
m = 0
n = 4

In [28]:
arr.shape[0]

4

In [24]:
arr1 = arr.copy()
arr1

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [29]:
if m >= 0 and m < arr.shape[0] and n>= 0 and n < arr.shape[0]:
    arr1[m,:] = arr[n,:]
    arr1[n,:] = arr[m,:]
arr1


array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [46]:
#Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside. 
n=1

In [47]:
a = np.zeros((n,n), dtype=int)
a

array([[0]])

In [48]:
a[0,:] = 1
a[-1,:] = 1
a[:,0] = 1
a[:,-1] = 1
a

array([[1]])